steps:

  # build docker image
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "build",
      "-t", "asia-northeast1-docker.pkg.dev/$PROJECT_ID/next-cloudrun/image:${SHORT_SHA}",
       "."
    ]

# Push artifacts
images:
  - "asia-northeast1-docker.pkg.dev/${PROJECT_ID}/next-cloudrun/image:${SHORT_SHA}"
