steps:

  # build docker image
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "build",
      "-t", "asia-northeast1-docker.pkg.dev/$PROJECT_ID/next-cloudrun/image:${SHORT_SHA}",
       "."
    ]

  # deploy cloud run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      "run", 
      "deploy",
      "next-cloudrun",
      "--image",
      "asia-northeast1-docker.pkg.dev/${PROJECT_ID}/next-cloudrun/image:${SHORT_SHA}",
      "--region",
      "asia-northeast1"
    ]

# Push artifacts
images:
  - "asia-northeast1-docker.pkg.dev/${PROJECT_ID}/next-cloudrun/image:${SHORT_SHA}"
